export default {
    INIT: 'INIT',
    
    ADD_PHOTO_REQUEST: 'INITADD_PHOTO_REQUEST',
    ADD_PHOTO_SUCCESS: 'ADD_PHOTO_SUCCESS',
    ADD_PHOTO_FAILED: 'ADD_PHOTO_FAILED',

    DELETE_PHOTO_REQUEST: 'DELETE_PHOTO_REQUEST',
    DELETE_PHOTO_SUCCESS: 'DELETE_PHOTO_SUCCESS',
    DELETE_PHOTO_FAILED: 'DELETE_PHOTO_FAILED',
    
}